import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import vue from "@the_tree/esbuild-plugin-vue3";
import copyStaticFiles from "esbuild-copy-static-files";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const jsOptions = {
    banner: {
        js: banner,
    },
    plugins: [
        vue({ isProd: true }),
        copyStaticFiles({
            src: './node_modules/sql.js/dist/sql-wasm.wasm',
            dest: './sql-wasm.wasm',
            overwrite: true,
        }),
    ],
    entryPoints: ['./src/plugin.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/closebrackets',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/comment',
        '@codemirror/fold',
        '@codemirror/gutter',
        '@codemirror/highlight',
        '@codemirror/history',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/matchbrackets',
        '@codemirror/panel',
        '@codemirror/rangeset',
        '@codemirror/rectangular-selection',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/stream-parser',
        '@codemirror/text',
        '@codemirror/tooltip',
        '@codemirror/view',
        ...builtins],
    format: 'cjs',
    target: 'es2016',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    minify: prod ? true : false,
    treeShaking: true,
    outfile: 'main.js',
};

const cssOptions = {
    entryPoints: ["./src/main.css"],
    outfile: "styles.css",
    bundle: true,
    allowOverwrite: true,
    minify: false,
};

if (prod) {
    await esbuild.build(jsOptions).catch(() => process.exit(1));
    await esbuild.build(cssOptions).catch(() => process.exit(1));
} else {
    const jsContext = await esbuild.context(jsOptions);
    await jsContext.watch();
    
    const cssContext = await esbuild.context(cssOptions);
    await cssContext.watch();
}
