import { defineConfig } from 'vite';
import { resolve, dirname } from 'path';
import vue from '@vitejs/plugin-vue';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 自定义插件来处理相对路径的 .vue 文件导入
function resolveVueImports() {
    return {
        name: 'resolve-vue-imports',
        resolveId(source: string, importer: string) {
            if (source.endsWith('.vue') && !source.startsWith('.') && !source.startsWith('/')) {
                const importerDir = dirname(importer);
                const resolved = resolve(importerDir, source);
                return resolved;
            }
            return null;
        }
    };

}

export default defineConfig(({ mode }) => {
    const isProd = mode === 'production';

    return {
        resolve: {
            alias: {
                '@': resolve(__dirname, 'src'),
                '@dict': resolve(__dirname, 'src/dictionary'),
                '@comp': resolve(__dirname, 'src/component')
            },
            extensions: ['.ts', '.tsx', '.js', '.jsx', '.vue', '.json']
        },
        plugins: [
            vue(),
            resolveVueImports(),
            {
                name: 'copy-wasm-file',
                writeBundle() {
                    const fs = require('fs');
                    const srcPath = resolve(__dirname, 'node_modules/sql.js/dist/sql-wasm.wasm');
                    const destPath = resolve(__dirname, 'sql-wasm.wasm');
                    if (fs.existsSync(srcPath)) {
                        fs.copyFileSync(srcPath, destPath);
                    }
                }
            },
            {
                name: 'clean-old-files',
                closeBundle() {
                    const fs = require('fs');
                    const path = require('path');
                    // 清理旧的构建文件
                    const oldFiles = ['main.css', 'plugin.css', 'main.js.map'];
                    oldFiles.forEach(file => {
                        const filePath = resolve(__dirname, file);
                        if (fs.existsSync(filePath)) {
                            fs.unlinkSync(filePath);
                        }
                    });
                }
            }
        ],
        build: {
            outDir: './',
            emptyOutDir: false,
            sourcemap: false,
            minify: isProd,
            target: 'es2016',
            // 禁用压缩时的静态资源内联
            assetsInlineLimit: 0,
            lib: {
                entry: resolve(__dirname, 'src/main.ts'),
                name: 'LanguageLearner',
                fileName: 'main',
                formats: ['cjs']
            },
            rollupOptions: {
                treeshake: true,
                external: [
                    'obsidian',
                    'electron',
                    '@codemirror/autocomplete',
                    '@codemirror/closebrackets',
                    '@codemirror/collab',
                    '@codemirror/commands',
                    '@codemirror/comment',
                    '@codemirror/fold',
                    '@codemirror/gutter',
                    '@codemirror/highlight',
                    '@codemirror/history',
                    '@codemirror/language',
                    '@codemirror/lint',
                    '@codemirror/matchbrackets',
                    '@codemirror/panel',
                    '@codemirror/rangeset',
                    '@codemirror/rectangular-selection',
                    '@codemirror/search',
                    '@codemirror/state',
                    '@codemirror/stream-parser',
                    '@codemirror/text',
                    '@codemirror/tooltip',
                    '@codemirror/view',
                    ...builtins],
                output: {
                    exports: 'auto',
                    banner,
                    globals: {
                        'obsidian': 'obsidian'
                    },
                    assetFileNames: (assetInfo) => {
                        // 将所有 CSS 文件统一命名为 styles.css
                        if (assetInfo.name && assetInfo.name.endsWith('.css')) {
                            return 'styles.css';
                        }
                        // 其他资源保持原名称
                        return assetInfo.name;
                    }
                }
            }
        },
        css: {
            devSourcemap: !isProd
        },
        // public 目录配置 - 禁用自动复制 public 目录文件
        // Obsidian 插件会手动管理资源文件
        publicDir: false
    };
});
